/**
 * Circuit geometry and track-data handling. No rendering and no race logic in here.
 *
 * Source data lives in src/data/circuits/<id>.json (generated by scripts/build_circuit.py from the
 * TUM FTM racetrack-database). All maths below is done in "map" coordinates (x east, y north, metres);
 * `toScene` converts to the three.js frame (x, y-up, z = -north) so nothing is mirrored.
 *
 * To add another circuit: run the build script on another CSV, then register it in CIRCUITS below.
 */
import silverstone from "../data/circuits/silverstone.json";

export interface CornerInfo {
  n: number; index: number; start_index: number; end_index: number; fraction: number;
  radius_m: number; turn: "left" | "right";
}
export interface Landmark { name: string; index: number; kind: "straight" | "corner"; length_m?: number }
export interface CircuitData {
  id: string; name: string; location: string; length_m: number; point_count: number; spacing_m: number;
  clockwise: boolean; points: number[][]; half_width_right_m: number[]; half_width_left_m: number[];
  start_index: number; sectors: { fractions: number[]; approximate: boolean };
  corners: CornerInfo[]; landmarks: Landmark[];
  pit_lane: { points: number[][]; entry_index_offset: number; exit_index_offset: number; box_index_offset: number;
    entry_distance_m: number; exit_distance_m: number; offset_m: number; approximate: boolean };
  source: { dataset: string; url: string; file: string; license: string; citation: string };
  limitations: string[];
}

export const CIRCUITS: Record<string, CircuitData> = { silverstone: silverstone as unknown as CircuitData };

export interface Pose { x: number; y: number; tx: number; ty: number }

export interface Circuit {
  data: CircuitData;
  n: number;
  length: number;
  step: number;
  x: Float64Array; y: Float64Array; tx: Float64Array; ty: Float64Array;
  hl: Float64Array; hr: Float64Array;
  /** signed curvature (1/m), positive = left turn, per centerline sample */
  kappa: Float64Array;
  pit: { x: Float64Array; y: Float64Array; tx: Float64Array; ty: Float64Array; cum: Float64Array;
    length: number; lineDist: number; entryDist: number; exitDist: number };
  /** pose at lap fraction f in [0,1), 0 = start/finish line */
  pointAt(f: number): Pose;
  /** pose at distance s (m) along the pit lane polyline */
  pitAt(s: number): Pose;
  /** nearest-centerline distance helper for scenery placement */
  distanceToTrack(px: number, py: number): number;
}

const wrap = (i: number, n: number) => ((i % n) + n) % n;

export function buildCircuit(data: CircuitData): Circuit {
  const n = data.point_count;
  const x = new Float64Array(n), y = new Float64Array(n);
  const tx = new Float64Array(n), ty = new Float64Array(n);
  const hl = new Float64Array(n), hr = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    x[i] = data.points[i][0];
    y[i] = data.points[i][1];
    hl[i] = data.half_width_left_m[i];
    hr[i] = data.half_width_right_m[i];
  }
  // rotate arrays so index 0 is the start/finish line
  const s0 = data.start_index;
  if (s0 !== 0) {
    const rot = (a: Float64Array) => Float64Array.from({ length: n }, (_, i) => a[wrap(i + s0, n)]);
    x.set(rot(x)); y.set(rot(y)); hl.set(rot(hl)); hr.set(rot(hr));
  }
  for (let i = 0; i < n; i++) {
    const dx = x[wrap(i + 1, n)] - x[wrap(i - 1, n)];
    const dy = y[wrap(i + 1, n)] - y[wrap(i - 1, n)];
    const l = Math.hypot(dx, dy) || 1;
    tx[i] = dx / l; ty[i] = dy / l;
  }
  const step = data.length_m / n;
  const kappa = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    const a = Math.atan2(ty[wrap(i - 2, n)], tx[wrap(i - 2, n)]), b = Math.atan2(ty[wrap(i + 2, n)], tx[wrap(i + 2, n)]);
    let d = b - a;
    while (d > Math.PI) d -= 2 * Math.PI;
    while (d < -Math.PI) d += 2 * Math.PI;
    kappa[i] = d / (4 * step);
  }

  // pit lane polyline
  const pp = data.pit_lane.points;
  const m = pp.length;
  const px = new Float64Array(m), py = new Float64Array(m), ptx = new Float64Array(m), pty = new Float64Array(m);
  const cum = new Float64Array(m);
  for (let i = 0; i < m; i++) {
    px[i] = pp[i][0]; py[i] = pp[i][1];
    if (i > 0) cum[i] = cum[i - 1] + Math.hypot(px[i] - px[i - 1], py[i] - py[i - 1]);
  }
  for (let i = 0; i < m; i++) {
    const a = Math.max(0, i - 1), b = Math.min(m - 1, i + 1);
    const dx = px[b] - px[a], dy = py[b] - py[a], l = Math.hypot(dx, dy) || 1;
    ptx[i] = dx / l; pty[i] = dy / l;
  }
  const lineIdx = -data.pit_lane.entry_index_offset; // pit polyline index sitting beside the start line
  const pit = { x: px, y: py, tx: ptx, ty: pty, cum, length: cum[m - 1], lineDist: cum[lineIdx],
    entryDist: cum[lineIdx], exitDist: cum[m - 1] - cum[lineIdx] };

  const pointAt = (f: number): Pose => {
    const u = wrap(f, 1) * n;
    const i = Math.floor(u), k = u - i, j = wrap(i + 1, n);
    const ttx = tx[i] * (1 - k) + tx[j] * k, tty = ty[i] * (1 - k) + ty[j] * k;
    const l = Math.hypot(ttx, tty) || 1;
    return { x: x[i] * (1 - k) + x[j] * k, y: y[i] * (1 - k) + y[j] * k, tx: ttx / l, ty: tty / l };
  };
  const pitAt = (s: number): Pose => {
    const d = Math.min(Math.max(s, 0), cum[m - 1]);
    let lo = 0, hi = m - 1;
    while (hi - lo > 1) { const mid = (lo + hi) >> 1; if (cum[mid] <= d) lo = mid; else hi = mid; }
    const seg = cum[hi] - cum[lo] || 1, k = (d - cum[lo]) / seg;
    const ttx = ptx[lo] * (1 - k) + ptx[hi] * k, tty = pty[lo] * (1 - k) + pty[hi] * k;
    const l = Math.hypot(ttx, tty) || 1;
    return { x: px[lo] * (1 - k) + px[hi] * k, y: py[lo] * (1 - k) + py[hi] * k, tx: ttx / l, ty: tty / l };
  };

  // coarse spatial hash for distance queries
  const cell = 80;
  const grid = new Map<string, number[]>();
  for (let i = 0; i < n; i++) {
    const key = `${Math.floor(x[i] / cell)},${Math.floor(y[i] / cell)}`;
    (grid.get(key) ?? grid.set(key, []).get(key)!).push(i);
  }
  const distanceToTrack = (qx: number, qy: number): number => {
    const cx = Math.floor(qx / cell), cy = Math.floor(qy / cell);
    let best = Infinity;
    for (let dx = -2; dx <= 2; dx++) for (let dy = -2; dy <= 2; dy++) {
      const arr = grid.get(`${cx + dx},${cy + dy}`);
      if (!arr) continue;
      for (const i of arr) best = Math.min(best, Math.hypot(qx - x[i], qy - y[i]));
    }
    return best;
  };

  return { data, n, length: data.length_m, step, x, y, tx, ty, hl, hr, kappa, pit, pointAt, pitAt, distanceToTrack };
}

const cache = new Map<string, Circuit>();
export function getCircuit(id: string): Circuit {
  const key = CIRCUITS[id] ? id : "silverstone";
  let c = cache.get(key);
  if (!c) { c = buildCircuit(CIRCUITS[key]); cache.set(key, c); }
  return c;
}

/** map (x east, y north) -> three.js scene (x, z = -north) */
export const sceneX = (x: number) => x;
export const sceneZ = (y: number) => -y;
/** yaw (rotation about scene Y) for a car whose local +X is its nose */
export const yawOf = (p: Pose) => Math.atan2(p.ty, p.tx);
